-- Legacy demo seed intentionally disabled.
--
-- MICHIRA must not ship hardcoded review records, sentiment statistics,
-- recurring problems, service scores, or emerging attractions. The current
-- database/setup.sh installs the schema only; the backend seeds the static
-- destination selector and all review intelligence is created from:
--
--   Apify Google Maps Reviews -> PostgreSQL -> Gemini -> aggregation
--
-- Keep this file as a migration-history marker rather than a data source.
